input_lvs = [
    {
        'X': (0, 150, 1),
        'name': 'Area',
        'terms': {
            'minimal': ('trapmf', 0, 0, 20, 40),
            'modest': ('trimf', 30, 50, 70),
            'comfortable': ('trapmf', 60, 70, 80, 100),
            'spacious': ('trapmf', 90, 110, 150, 150),
        }
    },

    {
        'X': (1, 52, 1),
        'name': 'Floor',
        'terms': {
            'lower': ('trapmf', 1, 1, 5, 10),
            'middle': ('trimf', 5, 15, 20),
            'upper': ('trapmf', 15, 25, 52, 52),
        }
    },

    {
        'X': (0, 65, 1),
        'name': 'Аge of buildinge',
        'terms': {
            'new building': ('trapmf', 0, 0, 5, 10),
            'young': ('trimf', 5, 10, 15),
            'middle-aged': ('trapmf', 10, 15, 20, 25),
            'old': ('trapmf', 20, 30, 65, 65),
        }
    },

    {
        'X': (0, 15, 0.1),
        'name': 'Distance to the city center',
        'terms': {
            'in the center': ('trapmf', 0, 0, 0.5, 1),
            'near the center': ('trapmf', 0.5, 1, 2, 4),
            'far from the center': ('trimf', 3, 5, 8),
            'on the outskirts': ('trapmf', 7, 10, 15, 15),
        }
    }
]

output_lv = {
    'X': (0, 6_000_000, 1_000),
    'name': 'The cost of real estate',
    'terms': {
        'economical': ('trapmf', 0, 0, 50_000, 65_000),
        'affordable': ('trapmf', 45_000, 75_000, 100_000, 110_000),
        'average': ('trapmf', 90_000, 125_000, 175_000, 200_000),
        'high': ('trapmf', 150_000, 250_000, 400_000, 500_000),
        'elite': ('trapmf', 400_000, 600_000, 800_000, 1_000_000),
        'luxurious': ('trapmf', 750_000, 1_000_000, 1_500_000, 2_000_000),
        'extremely expensive': ('trapmf', 1_500_000, 2_500_000, 6_000_000, 6_000_000),
    }
}


rule_base = [
(('minimal', 'lower', 'new building', 'in the center'), 'average'),
(('minimal', 'lower', 'new building', 'near the center'), 'affordable'),
(('minimal', 'lower', 'new building', 'far from the center'), 'affordable'),
(('minimal', 'lower', 'new building', 'on the outskirts'), 'affordable'),
(('minimal', 'lower', 'young', 'in the center'), 'affordable'),
(('minimal', 'lower', 'young', 'near the center'), 'affordable'),
(('minimal', 'lower', 'young', 'far from the center'), 'economical'),
(('minimal', 'lower', 'young', 'on the outskirts'), 'economical'),
(('minimal', 'lower', 'middle-aged', 'in the center'), 'affordable'),
(('minimal', 'lower', 'middle-aged', 'near the center'), 'economical'),
(('minimal', 'lower', 'middle-aged', 'far from the center'), 'economical'),
(('minimal', 'lower', 'middle-aged', 'on the outskirts'), 'economical'),
(('minimal', 'lower', 'old', 'in the center'), 'economical'),
(('minimal', 'lower', 'old', 'near the center'), 'economical'),
(('minimal', 'lower', 'old', 'far from the center'), 'economical'),
(('minimal', 'lower', 'old', 'on the outskirts'), 'economical'),
(('minimal', 'middle', 'new building', 'in the center'), 'average'),
(('minimal', 'middle', 'new building', 'near the center'), 'average'),
(('minimal', 'middle', 'new building', 'far from the center'), 'affordable'),
(('minimal', 'middle', 'new building', 'on the outskirts'), 'affordable'),
(('minimal', 'middle', 'young', 'in the center'), 'average'),
(('minimal', 'middle', 'young', 'near the center'), 'affordable'),
(('minimal', 'middle', 'young', 'far from the center'), 'affordable'),
(('minimal', 'middle', 'young', 'on the outskirts'), 'economical'),
(('minimal', 'middle', 'middle-aged', 'in the center'), 'affordable'),
(('minimal', 'middle', 'middle-aged', 'near the center'), 'affordable'),
(('minimal', 'middle', 'middle-aged', 'far from the center'), 'economical'),
(('minimal', 'middle', 'middle-aged', 'on the outskirts'), 'economical'),
(('minimal', 'middle', 'old', 'in the center'), 'affordable'),
(('minimal', 'middle', 'old', 'near the center'), 'economical'),
(('minimal', 'middle', 'old', 'far from the center'), 'economical'),
(('minimal', 'middle', 'old', 'on the outskirts'), 'economical'),
(('minimal', 'upper', 'new building', 'in the center'), 'average'),
(('minimal', 'upper', 'new building', 'near the center'), 'average'),
(('minimal', 'upper', 'new building', 'far from the center'), 'average'),
(('minimal', 'upper', 'new building', 'on the outskirts'), 'affordable'),
(('minimal', 'upper', 'young', 'in the center'), 'average'),
(('minimal', 'upper', 'young', 'near the center'), 'affordable'),
(('minimal', 'upper', 'young', 'far from the center'), 'affordable'),
(('minimal', 'upper', 'young', 'on the outskirts'), 'affordable'),
(('minimal', 'upper', 'middle-aged', 'in the center'), 'affordable'),
(('minimal', 'upper', 'middle-aged', 'near the center'), 'affordable'),
(('minimal', 'upper', 'middle-aged', 'far from the center'), 'affordable'),
(('minimal', 'upper', 'middle-aged', 'on the outskirts'), 'economical'),
(('minimal', 'upper', 'old', 'in the center'), 'affordable'),
(('minimal', 'upper', 'old', 'near the center'), 'economical'),
(('minimal', 'upper', 'old', 'far from the center'), 'economical'),
(('minimal', 'upper', 'old', 'on the outskirts'), 'economical'),
(('modest', 'lower', 'new building', 'in the center'), 'high'),
(('modest', 'lower', 'new building', 'near the center'), 'high'),
(('modest', 'lower', 'new building', 'far from the center'), 'average'),
(('modest', 'lower', 'new building', 'on the outskirts'), 'average'),
(('modest', 'lower', 'young', 'in the center'), 'high'),
(('modest', 'lower', 'young', 'near the center'), 'average'),
(('modest', 'lower', 'young', 'far from the center'), 'average'),
(('modest', 'lower', 'young', 'on the outskirts'), 'affordable'),
(('modest', 'lower', 'middle-aged', 'in the center'), 'average'),
(('modest', 'lower', 'middle-aged', 'near the center'), 'average'),
(('modest', 'lower', 'middle-aged', 'far from the center'), 'affordable'),
(('modest', 'lower', 'middle-aged', 'on the outskirts'), 'affordable'),
(('modest', 'lower', 'old', 'in the center'), 'average'),
(('modest', 'lower', 'old', 'near the center'), 'affordable'),
(('modest', 'lower', 'old', 'far from the center'), 'affordable'),
(('modest', 'lower', 'old', 'on the outskirts'), 'economical'),
(('modest', 'middle', 'new building', 'in the center'), 'high'),
(('modest', 'middle', 'new building', 'near the center'), 'high'),
(('modest', 'middle', 'new building', 'far from the center'), 'high'),
(('modest', 'middle', 'new building', 'on the outskirts'), 'average'),
(('modest', 'middle', 'young', 'in the center'), 'high'),
(('modest', 'middle', 'young', 'near the center'), 'high'),
(('modest', 'middle', 'young', 'far from the center'), 'average'),
(('modest', 'middle', 'young', 'on the outskirts'), 'average'),
(('modest', 'middle', 'middle-aged', 'in the center'), 'average'),
(('modest', 'middle', 'middle-aged', 'near the center'), 'average'),
(('modest', 'middle', 'middle-aged', 'far from the center'), 'average'),
(('modest', 'middle', 'middle-aged', 'on the outskirts'), 'affordable'),
(('modest', 'middle', 'old', 'in the center'), 'average'),
(('modest', 'middle', 'old', 'near the center'), 'average'),
(('modest', 'middle', 'old', 'far from the center'), 'affordable'),
(('modest', 'middle', 'old', 'on the outskirts'), 'affordable'),
(('modest', 'upper', 'new building', 'in the center'), 'high'),
(('modest', 'upper', 'new building', 'near the center'), 'high'),
(('modest', 'upper', 'new building', 'far from the center'), 'high'),
(('modest', 'upper', 'new building', 'on the outskirts'), 'high'),
(('modest', 'upper', 'young', 'in the center'), 'high'),
(('modest', 'upper', 'young', 'near the center'), 'high'),
(('modest', 'upper', 'young', 'far from the center'), 'average'),
(('modest', 'upper', 'young', 'on the outskirts'), 'average'),
(('modest', 'upper', 'middle-aged', 'in the center'), 'high'),
(('modest', 'upper', 'middle-aged', 'near the center'), 'average'),
(('modest', 'upper', 'middle-aged', 'far from the center'), 'average'),
(('modest', 'upper', 'middle-aged', 'on the outskirts'), 'average'),
(('modest', 'upper', 'old', 'in the center'), 'average'),
(('modest', 'upper', 'old', 'near the center'), 'average'),
(('modest', 'upper', 'old', 'far from the center'), 'affordable'),
(('modest', 'upper', 'old', 'on the outskirts'), 'affordable'),
(('comfortable', 'lower', 'new building', 'in the center'), 'high'),
(('comfortable', 'lower', 'new building', 'near the center'), 'high'),
(('comfortable', 'lower', 'new building', 'far from the center'), 'high'),
(('comfortable', 'lower', 'new building', 'on the outskirts'), 'high'),
(('comfortable', 'lower', 'young', 'in the center'), 'high'),
(('comfortable', 'lower', 'young', 'near the center'), 'high'),
(('comfortable', 'lower', 'young', 'far from the center'), 'high'),
(('comfortable', 'lower', 'young', 'on the outskirts'), 'high'),
(('comfortable', 'lower', 'middle-aged', 'in the center'), 'high'),
(('comfortable', 'lower', 'middle-aged', 'near the center'), 'high'),
(('comfortable', 'lower', 'middle-aged', 'far from the center'), 'high'),
(('comfortable', 'lower', 'middle-aged', 'on the outskirts'), 'average'),
(('comfortable', 'lower', 'old', 'in the center'), 'high'),
(('comfortable', 'lower', 'old', 'near the center'), 'high'),
(('comfortable', 'lower', 'old', 'far from the center'), 'average'),
(('comfortable', 'lower', 'old', 'on the outskirts'), 'average'),
(('comfortable', 'middle', 'new building', 'in the center'), 'elite'),
(('comfortable', 'middle', 'new building', 'near the center'), 'high'),
(('comfortable', 'middle', 'new building', 'far from the center'), 'high'),
(('comfortable', 'middle', 'new building', 'on the outskirts'), 'high'),
(('comfortable', 'middle', 'young', 'in the center'), 'high'),
(('comfortable', 'middle', 'young', 'near the center'), 'high'),
(('comfortable', 'middle', 'young', 'far from the center'), 'high'),
(('comfortable', 'middle', 'young', 'on the outskirts'), 'high'),
(('comfortable', 'middle', 'middle-aged', 'in the center'), 'high'),
(('comfortable', 'middle', 'middle-aged', 'near the center'), 'high'),
(('comfortable', 'middle', 'middle-aged', 'far from the center'), 'high'),
(('comfortable', 'middle', 'middle-aged', 'on the outskirts'), 'high'),
(('comfortable', 'middle', 'old', 'in the center'), 'high'),
(('comfortable', 'middle', 'old', 'near the center'), 'high'),
(('comfortable', 'middle', 'old', 'far from the center'), 'high'),
(('comfortable', 'middle', 'old', 'on the outskirts'), 'average'),
(('comfortable', 'upper', 'new building', 'in the center'), 'elite'),
(('comfortable', 'upper', 'new building', 'near the center'), 'elite'),
(('comfortable', 'upper', 'new building', 'far from the center'), 'high'),
(('comfortable', 'upper', 'new building', 'on the outskirts'), 'high'),
(('comfortable', 'upper', 'young', 'in the center'), 'elite'),
(('comfortable', 'upper', 'young', 'near the center'), 'high'),
(('comfortable', 'upper', 'young', 'far from the center'), 'high'),
(('comfortable', 'upper', 'young', 'on the outskirts'), 'high'),
(('comfortable', 'upper', 'middle-aged', 'in the center'), 'high'),
(('comfortable', 'upper', 'middle-aged', 'near the center'), 'high'),
(('comfortable', 'upper', 'middle-aged', 'far from the center'), 'high'),
(('comfortable', 'upper', 'middle-aged', 'on the outskirts'), 'high'),
(('comfortable', 'upper', 'old', 'in the center'), 'high'),
(('comfortable', 'upper', 'old', 'near the center'), 'high'),
(('comfortable', 'upper', 'old', 'far from the center'), 'high'),
(('comfortable', 'upper', 'old', 'on the outskirts'), 'high'),
(('spacious', 'lower', 'new building', 'in the center'), 'luxurious'),
(('spacious', 'lower', 'new building', 'near the center'), 'elite'),
(('spacious', 'lower', 'new building', 'far from the center'), 'elite'),
(('spacious', 'lower', 'new building', 'on the outskirts'), 'elite'),
(('spacious', 'lower', 'young', 'in the center'), 'elite'),
(('spacious', 'lower', 'young', 'near the center'), 'elite'),
(('spacious', 'lower', 'young', 'far from the center'), 'elite'),
(('spacious', 'lower', 'young', 'on the outskirts'), 'high'),
(('spacious', 'lower', 'middle-aged', 'in the center'), 'elite'),
(('spacious', 'lower', 'middle-aged', 'near the center'), 'high'),
(('spacious', 'lower', 'middle-aged', 'far from the center'), 'high'),
(('spacious', 'lower', 'middle-aged', 'on the outskirts'), 'high'),
(('spacious', 'lower', 'old', 'in the center'), 'high'),
(('spacious', 'lower', 'old', 'near the center'), 'high'),
(('spacious', 'lower', 'old', 'far from the center'), 'high'),
(('spacious', 'lower', 'old', 'on the outskirts'), 'high'),
(('spacious', 'middle', 'new building', 'in the center'), 'extremely expensive'),
(('spacious', 'middle', 'new building', 'near the center'), 'luxurious'),
(('spacious', 'middle', 'new building', 'far from the center'), 'elite'),
(('spacious', 'middle', 'new building', 'on the outskirts'), 'elite'),
(('spacious', 'middle', 'young', 'in the center'), 'luxurious'),
(('spacious', 'middle', 'young', 'near the center'), 'elite'),
(('spacious', 'middle', 'young', 'far from the center'), 'elite'),
(('spacious', 'middle', 'young', 'on the outskirts'), 'elite'),
(('spacious', 'middle', 'middle-aged', 'in the center'), 'elite'),
(('spacious', 'middle', 'middle-aged', 'near the center'), 'elite'),
(('spacious', 'middle', 'middle-aged', 'far from the center'), 'high'),
(('spacious', 'middle', 'middle-aged', 'on the outskirts'), 'high'),
(('spacious', 'middle', 'old', 'in the center'), 'elite'),
(('spacious', 'middle', 'old', 'near the center'), 'high'),
(('spacious', 'middle', 'old', 'far from the center'), 'high'),
(('spacious', 'middle', 'old', 'on the outskirts'), 'high'),
(('spacious', 'upper', 'new building', 'in the center'), 'extremely expensive'),
(('spacious', 'upper', 'new building', 'near the center'), 'extremely expensive'),
(('spacious', 'upper', 'new building', 'far from the center'), 'luxurious'),
(('spacious', 'upper', 'new building', 'on the outskirts'), 'elite'),
(('spacious', 'upper', 'young', 'in the center'), 'extremely expensive'),
(('spacious', 'upper', 'young', 'near the center'), 'luxurious'),
(('spacious', 'upper', 'young', 'far from the center'), 'elite'),
(('spacious', 'upper', 'young', 'on the outskirts'), 'elite'),
(('spacious', 'upper', 'middle-aged', 'in the center'), 'elite'),
(('spacious', 'upper', 'middle-aged', 'near the center'), 'elite'),
(('spacious', 'upper', 'middle-aged', 'far from the center'), 'elite'),
(('spacious', 'upper', 'middle-aged', 'on the outskirts'), 'high'),
(('spacious', 'upper', 'old', 'in the center'), 'elite'),
(('spacious', 'upper', 'old', 'near the center'), 'elite'),
(('spacious', 'upper', 'old', 'far from the center'), 'high'),
(('spacious', 'upper', 'old', 'on the outskirts'), 'high'),
]