input_lvs = [
    {
        'X': (0, 1.01, 0.01),
        'name': 'relevance level',
        'terms': {
            'irrelevant': ('trapmf', 0, 0, 0.2, 0.3),
            'low relevant': ('trapmf', 0.2, 0.3, 0.4, 0.6),
            'possible': ('trimf', 0.4, 0.55, 0.7),
            'overwhelming': ('trapmf', 0.6, 0.7, 1, 1)
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'institution technical level',
        'terms': {
            'miserable': ('trapmf', 0, 0, 0.2, 0.4),
            'below middle': ('trapmf', 0.25, 0.4, 0.6, 0.75),
            'satisfying': ('trapmf', 0.6, 0.69, 0.7, 0.77),
            'positive': ('trapmf', 0.8, 0.85, 0.9, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'student satisfaction',
        'terms': {
            'low': ('trapmf', 0, 0.1, 0.22, 0.3),
            'poor': ('trapmf', 0.3, 0.35, 0.39, 0.4),
            'avarage': ('trapmf', 0.45, 0.5, 0.55, 0.6),
            'high': ('trapmf', 0.7, 0.9, 1, 1)
        }
    },
    {
        'X': (0, 1.01, 0.01),
        'name': 'program propensity',
        'terms': {
            'small': ('trapmf', 0, 0, 0.4, 0.6),
            'median': ('trapmf', 0.4, 0.5, 0.7, 0.9),
            'towering': ('trapmf', 0.7, 0.9, 1, 1 )
        }
    }
]

output_lv = {
    'X': (0, 1.01, 0.01),
    'name': 'Class',
    'terms': {
        'Very Low': ('trapmf', 0, 0, 0.1, 0.2),
        'Low': ('trapmf', 0.25, 0.29, 0.3, 0.32),
        'Favorable': ('trimf', 0.36, 0.4, 0.45),
        'Average': ('trapmf', 0.49, 0.5, 0.55, 0.59),
        'High': ('trimf', 0.6, 0.66, 0.7),
        'Very high': ('trapmf', 0.75, 0.77, 0.8, 0.9),
        'Extremely high': ('trapmf', 0.8, 0.95, 1, 1),
    }
}


rule_base = [
(('irrelevant', 'miserable', 'low', 'small'), 'Very low'),
(('irrelevant', 'miserable', 'low', 'median'), 'Very low'),   
(('irrelevant', 'miserable', 'low', 'towering'), 'Very low'), 
(('irrelevant', 'miserable', 'poor', 'small'), 'Very low'),   
(('irrelevant', 'miserable', 'poor', 'median'), 'Very low'),  
(('irrelevant', 'miserable', 'poor', 'towering'), 'Very low'),
(('irrelevant', 'miserable', 'avarage', 'small'), 'Very low'),
(('irrelevant', 'miserable', 'avarage', 'median'), 'Low'),    
(('irrelevant', 'miserable', 'avarage', 'towering'), 'Low'),  
(('irrelevant', 'miserable', 'high', 'small'), 'Low'),        
(('irrelevant', 'miserable', 'high', 'median'), 'Favorable'),
(('irrelevant', 'miserable', 'high', 'towering'), 'Average'),
(('irrelevant', 'below middle', 'low', 'small'), 'Very low'),
(('irrelevant', 'below middle', 'low', 'median'), 'Very low'),
(('irrelevant', 'below middle', 'low', 'towering'), 'Very low'),
(('irrelevant', 'below middle', 'poor', 'small'), 'Very low'),
(('irrelevant', 'below middle', 'poor', 'median'), 'Very low'),
(('irrelevant', 'below middle', 'poor', 'towering'), 'Very low'),
(('irrelevant', 'below middle', 'avarage', 'small'), 'Very low'),
(('irrelevant', 'below middle', 'avarage', 'median'), 'Low'),
(('irrelevant', 'below middle', 'avarage', 'towering'), 'Favorable'),
(('irrelevant', 'below middle', 'high', 'small'), 'Favorable'),
(('irrelevant', 'below middle', 'high', 'median'), 'Average'),
(('irrelevant', 'below middle', 'high', 'towering'), 'Average'),
(('irrelevant', 'satisfying', 'low', 'small'), 'Very low'),
(('irrelevant', 'satisfying', 'low', 'median'), 'Very low'),
(('irrelevant', 'satisfying', 'low', 'towering'), 'Very low'),
(('irrelevant', 'satisfying', 'poor', 'small'), 'Very low'),
(('irrelevant', 'satisfying', 'poor', 'median'), 'Very low'),
(('irrelevant', 'satisfying', 'poor', 'towering'), 'Low'),
(('irrelevant', 'satisfying', 'avarage', 'small'), 'Low'),
(('irrelevant', 'satisfying', 'avarage', 'median'), 'Low'),
(('irrelevant', 'satisfying', 'avarage', 'towering'), 'Favorable'),
(('irrelevant', 'satisfying', 'high', 'small'), 'Favorable'),
(('irrelevant', 'satisfying', 'high', 'median'), 'Average'),
(('irrelevant', 'satisfying', 'high', 'towering'), 'High'),
(('irrelevant', 'positive', 'low', 'small'), 'Very low'),
(('irrelevant', 'positive', 'low', 'median'), 'Very low'),
(('irrelevant', 'positive', 'low', 'towering'), 'Very low'),
(('irrelevant', 'positive', 'poor', 'small'), 'Very low'),
(('irrelevant', 'positive', 'poor', 'median'), 'Very low'),
(('irrelevant', 'positive', 'poor', 'towering'), 'Low'),
(('irrelevant', 'positive', 'avarage', 'small'), 'Low'),
(('irrelevant', 'positive', 'avarage', 'median'), 'Favorable'),
(('irrelevant', 'positive', 'avarage', 'towering'), 'Favorable'),
(('irrelevant', 'positive', 'high', 'small'), 'Favorable'),
(('irrelevant', 'positive', 'high', 'median'), 'High'),
(('irrelevant', 'positive', 'high', 'towering'), 'High'),
(('low relevant', 'miserable', 'low', 'small'), 'Very low'),
(('low relevant', 'miserable', 'low', 'median'), 'Very low'),
(('low relevant', 'miserable', 'low', 'towering'), 'Low'),
(('low relevant', 'miserable', 'poor', 'small'), 'Very low'),
(('low relevant', 'miserable', 'poor', 'median'), 'Low'),
(('low relevant', 'miserable', 'poor', 'towering'), 'Favorable'),
(('low relevant', 'miserable', 'avarage', 'small'), 'Low'),
(('low relevant', 'miserable', 'avarage', 'median'), 'Average'),
(('low relevant', 'miserable', 'avarage', 'towering'), 'Average'),
(('low relevant', 'miserable', 'high', 'small'), 'Average'),
(('low relevant', 'miserable', 'high', 'median'), 'High'),
(('low relevant', 'miserable', 'high', 'towering'), 'Very high'),
(('low relevant', 'below middle', 'low', 'small'), 'Very low'),
(('low relevant', 'below middle', 'low', 'median'), 'Low'),
(('low relevant', 'below middle', 'low', 'towering'), 'Low'),
(('low relevant', 'below middle', 'poor', 'small'), 'Very low'),
(('low relevant', 'below middle', 'poor', 'median'), 'Low'),
(('low relevant', 'below middle', 'poor', 'towering'), 'Favorable'),
(('low relevant', 'below middle', 'avarage', 'small'), 'Favorable'),
(('low relevant', 'below middle', 'avarage', 'median'), 'Average'),
(('low relevant', 'below middle', 'avarage', 'towering'), 'High'),
(('low relevant', 'below middle', 'high', 'small'), 'High'),
(('low relevant', 'below middle', 'high', 'median'), 'Very high'),
(('low relevant', 'below middle', 'high', 'towering'), 'Very high'),
(('low relevant', 'satisfying', 'low', 'small'), 'Very low'),
(('low relevant', 'satisfying', 'low', 'median'), 'Low'),
(('low relevant', 'satisfying', 'low', 'towering'), 'Low'),
(('low relevant', 'satisfying', 'poor', 'small'), 'Low'),
(('low relevant', 'satisfying', 'poor', 'median'), 'Favorable'),
(('low relevant', 'satisfying', 'poor', 'towering'), 'Favorable'),
(('low relevant', 'satisfying', 'avarage', 'small'), 'Favorable'),
(('low relevant', 'satisfying', 'avarage', 'median'), 'Average'),
(('low relevant', 'satisfying', 'avarage', 'towering'), 'High'),
(('low relevant', 'satisfying', 'high', 'small'), 'High'),
(('low relevant', 'satisfying', 'high', 'median'), 'Very high'),
(('low relevant', 'satisfying', 'high', 'towering'), 'Very high'),
(('low relevant', 'positive', 'low', 'small'), 'Very low'),
(('low relevant', 'positive', 'low', 'median'), 'Low'),
(('low relevant', 'positive', 'low', 'towering'), 'Favorable'),
(('low relevant', 'positive', 'poor', 'small'), 'Low'),
(('low relevant', 'positive', 'poor', 'median'), 'Favorable'),
(('low relevant', 'positive', 'poor', 'towering'), 'Average'),
(('low relevant', 'positive', 'avarage', 'small'), 'Average'),
(('low relevant', 'positive', 'avarage', 'median'), 'High'),
(('low relevant', 'positive', 'avarage', 'towering'), 'High'),
(('low relevant', 'positive', 'high', 'small'), 'High'),
(('low relevant', 'positive', 'high', 'median'), 'Very high'),
(('low relevant', 'positive', 'high', 'towering'), 'Extremely high'),
(('possible', 'miserable', 'low', 'small'), 'Low'),
(('possible', 'miserable', 'low', 'median'), 'Favorable'),
(('possible', 'miserable', 'low', 'towering'), 'Favorable'),
(('possible', 'miserable', 'poor', 'small'), 'Low'),
(('possible', 'miserable', 'poor', 'median'), 'Favorable'),
(('possible', 'miserable', 'poor', 'towering'), 'Average'),
(('possible', 'miserable', 'avarage', 'small'), 'Average'),
(('possible', 'miserable', 'avarage', 'median'), 'High'),
(('possible', 'miserable', 'avarage', 'towering'), 'Very high'),
(('possible', 'miserable', 'high', 'small'), 'Very high'),
(('possible', 'miserable', 'high', 'median'), 'Very high'),
(('possible', 'miserable', 'high', 'towering'), 'Extremely high'),
(('possible', 'below middle', 'low', 'small'), 'Low'),
(('possible', 'below middle', 'low', 'median'), 'Favorable'),
(('possible', 'below middle', 'low', 'towering'), 'Average'),
(('possible', 'below middle', 'poor', 'small'), 'Favorable'),
(('possible', 'below middle', 'poor', 'median'), 'Average'),
(('possible', 'below middle', 'poor', 'towering'), 'Average'),
(('possible', 'below middle', 'avarage', 'small'), 'Average'),
(('possible', 'below middle', 'avarage', 'median'), 'High'),
(('possible', 'below middle', 'avarage', 'towering'), 'Very high'),
(('possible', 'below middle', 'high', 'small'), 'Very high'),
(('possible', 'below middle', 'high', 'median'), 'Extremely high'),
(('possible', 'below middle', 'high', 'towering'), 'Extremely high'),
(('possible', 'satisfying', 'low', 'small'), 'Low'),
(('possible', 'satisfying', 'low', 'median'), 'Favorable'),
(('possible', 'satisfying', 'low', 'towering'), 'Average'),
(('possible', 'satisfying', 'poor', 'small'), 'Favorable'),
(('possible', 'satisfying', 'poor', 'median'), 'Average'),
(('possible', 'satisfying', 'poor', 'towering'), 'High'),
(('possible', 'satisfying', 'avarage', 'small'), 'High'),
(('possible', 'satisfying', 'avarage', 'median'), 'Very high'),
(('possible', 'satisfying', 'avarage', 'towering'), 'Very high'),
(('possible', 'satisfying', 'high', 'small'), 'Very high'),
(('possible', 'satisfying', 'high', 'median'), 'Extremely high'),
(('possible', 'satisfying', 'high', 'towering'), 'Extremely high'),
(('possible', 'positive', 'low', 'small'), 'Favorable'),
(('possible', 'positive', 'low', 'median'), 'Average'),
(('possible', 'positive', 'low', 'towering'), 'Average'),
(('possible', 'positive', 'poor', 'small'), 'Favorable'),
(('possible', 'positive', 'poor', 'median'), 'High'),
(('possible', 'positive', 'poor', 'towering'), 'High'),
(('possible', 'positive', 'avarage', 'small'), 'High'),
(('possible', 'positive', 'avarage', 'median'), 'Very high'),
(('possible', 'positive', 'avarage', 'towering'), 'Extremely high'),
(('possible', 'positive', 'high', 'small'), 'Very high'),
(('possible', 'positive', 'high', 'median'), 'Extremely high'),
(('possible', 'positive', 'high', 'towering'), 'Extremely high'),
(('overwhelming', 'miserable', 'low', 'small'), 'Favorable'),
(('overwhelming', 'miserable', 'low', 'median'), 'Average'),
(('overwhelming', 'miserable', 'low', 'towering'), 'High'),
(('overwhelming', 'miserable', 'poor', 'small'), 'Average'),
(('overwhelming', 'miserable', 'poor', 'median'), 'High'),
(('overwhelming', 'miserable', 'poor', 'towering'), 'High'),
(('overwhelming', 'miserable', 'avarage', 'small'), 'High'),
(('overwhelming', 'miserable', 'avarage', 'median'), 'Very high'),
(('overwhelming', 'miserable', 'avarage', 'towering'), 'Extremely high'),
(('overwhelming', 'miserable', 'high', 'small'), 'Extremely high'),
(('overwhelming', 'miserable', 'high', 'median'), 'Extremely high'),
(('overwhelming', 'miserable', 'high', 'towering'), 'Extremely high'),
(('overwhelming', 'below middle', 'low', 'small'), 'Favorable'),
(('overwhelming', 'below middle', 'low', 'median'), 'Average'),
(('overwhelming', 'below middle', 'low', 'towering'), 'High'),
(('overwhelming', 'below middle', 'poor', 'small'), 'Average'),
(('overwhelming', 'below middle', 'poor', 'median'), 'High'),
(('overwhelming', 'below middle', 'poor', 'towering'), 'Very high'),
(('overwhelming', 'below middle', 'avarage', 'small'), 'Very high'),
(('overwhelming', 'below middle', 'avarage', 'median'), 'Extremely high'),
(('overwhelming', 'below middle', 'avarage', 'towering'), 'Extremely high'),
(('overwhelming', 'below middle', 'high', 'small'), 'Extremely high'),
(('overwhelming', 'below middle', 'high', 'median'), 'Extremely high'),
(('overwhelming', 'below middle', 'high', 'towering'), 'Extremely high'),
(('overwhelming', 'satisfying', 'low', 'small'), 'Average'),
(('overwhelming', 'satisfying', 'low', 'median'), 'High'),
(('overwhelming', 'satisfying', 'low', 'towering'), 'High'),
(('overwhelming', 'satisfying', 'poor', 'small'), 'Average'),
(('overwhelming', 'satisfying', 'poor', 'median'), 'Very high'),
(('overwhelming', 'satisfying', 'poor', 'towering'), 'Very high'),
(('overwhelming', 'satisfying', 'avarage', 'small'), 'Very high'),
(('overwhelming', 'satisfying', 'avarage', 'median'), 'Extremely high'),
(('overwhelming', 'satisfying', 'avarage', 'towering'), 'Extremely high'),
(('overwhelming', 'satisfying', 'high', 'small'), 'Extremely high'),
(('overwhelming', 'satisfying', 'high', 'median'), 'Extremely high'),
(('overwhelming', 'satisfying', 'high', 'towering'), 'Extremely high'),
(('overwhelming', 'positive', 'low', 'small'), 'Average'),
(('overwhelming', 'positive', 'low', 'median'), 'High'),
(('overwhelming', 'positive', 'low', 'towering'), 'Very high'),
(('overwhelming', 'positive', 'poor', 'small'), 'High'),
(('overwhelming', 'positive', 'poor', 'median'), 'Very high'),
(('overwhelming', 'positive', 'poor', 'towering'), 'Very high'),
(('overwhelming', 'positive', 'avarage', 'small'), 'Very high'),
(('overwhelming', 'positive', 'avarage', 'median'), 'Extremely high'),
(('overwhelming', 'positive', 'avarage', 'towering'), 'Extremely high'),
(('overwhelming', 'positive', 'high', 'small'), 'Extremely high'),
(('overwhelming', 'positive', 'high', 'median'), 'Extremely high'),
(('overwhelming', 'positive', 'high', 'towering'), 'Extremely high')]